[package]
name = "emuchip-8"
version = "0.1.0"
authors = ["Gianluca Bargelli <gianluca.bargelli@algolia.com>"]
edition = "2018"


[dependencies]
rand = "0.6.4"
wasm-bindgen = "0.2.32"

[target.'cfg(target_arch = "x86_64")'.dependencies]
sdl2 = "0.32"

[lib]
crate-type = ["cdylib", "rlib"]